{% set version = "isti_v0.2.2" %}

package:
        name: gmprocess
        version: {{ version }}

source:
        url: https://github.com/alexanderschnackenberg/groundmotion-processing/archive/{{ version }}.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - cython
    - numpy
    - pip
  run:
    - configobj
    - impactutils
    - lxml
    - obspy
    - openpyxl
    - python >=3.6
    - pyyaml
    - requests
    - vcrpy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - gmprocess
